package Enums

enum class RestaurantManagerOptions {
    ADD_FOOD_TO_RESTAURANT,
    ALTER_MENU_ITEMS,
    ADD_TIMING_FOR_FOOD,
    REMOVE_TIMING_FOR_FOOD,
    DELETE_MENU_ITEMS,
    SHOW_ALL_FOOD_ITEMS,
    GET_TIME_SPECIFIC_FOOD_ITEMS,
    SET_RESTAURANT_STATUS,
    VIEW_ORDERS_GOT,
    SET_STATUS_PREPARING,
    SET_STATUS_PREPARED,
    BACK;
}